import type { TargetLocale } from "./product-config";

type MessageParameters = Readonly<Record<string, string | number>>;

const ENGLISH_MESSAGES: Readonly<Record<string, string>> = {
  "勾选后自动获取译文，首次收录需要一些时间。": "Selecting a plugin fetches translations automatically. Initial setup may take some time.",
  "运行期间每 15 分钟自动检查新插件，也可点击“重新检查插件”立即检查。": "New plugins are checked every 15 minutes while Obsidian is running. Select “Recheck plugins” to check now.",
  "首次收录需要一些时间，期间可正常使用插件。": "Initial setup may take some time. You can keep using the plugin meanwhile.",
  "点击“重新检查插件”可立即检查，无需等待下一轮。": "Select “Recheck plugins” to check now instead of waiting for the next check.",
  "仅处理已选插件": "Selected plugins only",
  "译文按版本匹配": "Version-matched translations",
  "仅处理官方社区目录中来源可验证的插件；未收录或来源暂时无法确认时，会保留原文并显示原因。": "Only plugins with verifiable sources in the official community directory are processed. Unlisted or temporarily unverifiable sources keep their original text, with the reason shown.",
  "当前多数译文由机器翻译生成，未经人工校对；插件管理器会标明译文来源。": "Most translations are machine-generated and have not been human reviewed. The plugin manager identifies their source.",
  "优先保留插件自带的目标语言，补齐仍显示原文的界面。语枢自身界面目前支持简体中文和英语，其他语言使用英语界面。": "Preserve the plugin's built-in target language and fill remaining source text. The Trans-Hub interface supports Simplified Chinese and English; other selections use English.",
  "勾选后自动获取匹配译文；首次处理或缺失译文可能需要等待，可在管理器中查看进度与原因。": "Selecting a plugin automatically fetches matching translations. Initial processing or missing translations may take time; check progress and reasons in the manager.",
  "进度可能已过期，请检查进度。": "Progress may be out of date. Check progress again.",
  "已断开授权；本机清理未全部完成：{message}。请使用高级选项中的恢复操作检查文件。": "Authorization is disconnected, but local cleanup is incomplete: {message}. Use the restore action in Advanced options to check files.",
  "暂时无法更新进度，当前显示上次结果。请稍后检查进度。": "Progress is temporarily unavailable. Showing the previous result; check progress again later.",
  "已获取 {translated}/{total} 条匹配界面译文，{missing} 条保留原文": "Fetched {translated}/{total} matching UI translations; {missing} keep their original text",
  "已获取 {translated}/{total} 条匹配界面译文": "Fetched {translated}/{total} matching UI translations",
  "已恢复 {restored} 个插件文件；{conflicts} 个需处理。重新加载目标插件后生效。": "Restored {restored} plugin files; {conflicts} need attention. Reload the affected plugins to apply changes.",
  "恢复此插件的原始文件；如有外部修改，将先保留文件并提示。": "Restore the original plugin file. External changes are preserved and reported.",
  "写入与当前版本匹配的静态译文并保存备份，需要重新加载此插件。": "Write matching static translations with a backup. Reload this plugin afterwards.",
  "已写入 {applied} 条静态译文。重新加载目标插件后生效。": "Wrote {applied} static translations. Reload the affected plugin to apply them.",
  "插件文件已变化，未写入补丁。请检查此插件的安装状态。": "The plugin file changed, so no patch was written. Check its installation.",
  "当前没有可写入的匹配译文。请稍后检查进度。": "No matching translations can be written yet. Check progress later.",
  "译文语言": "Translation language",
  "为已启用的社区插件显示译文。默认不修改插件文件，始终不修改笔记正文。": "Localize enabled community plugins. Plugin files stay untouched by default; note content is never modified.",
  "选择其他插件的译文语言。语枢界面目前支持简体中文和英语，其他语言使用英语界面。": "Choose the translation language for other plugins. The Trans-Hub interface supports Simplified Chinese and English; other selections use English.",
  "选择需要本地化的插件，查看译文进度或处理问题。": "Choose plugins to localize, check translation progress, and resolve issues.",
  "高级选项": "Advanced options",
  "仅在普通本地化无法覆盖时使用。允许为单个插件写入匹配的静态译文，并先备份；应用或恢复后需重新加载该插件。": "Use only when runtime localization cannot reach the text. Allow matching static translations to be written per plugin, with a backup. Reload the plugin after applying or restoring.",
  "已允许兼容补丁，请在插件管理器中为单个插件应用。": "Compatibility patches are allowed. Apply them per plugin in the manager.",
  "恢复所有兼容补丁": "Restore all compatibility patches",
  "也会检查未启用的插件；遇到外部改动时保留文件并列出需处理项。": "Also check disabled plugins. Preserve externally changed files and list items needing attention.",
  "恢复原始文件": "Restore original files",
  "仅支持官方社区目录中来源可验证的插件。离线时可继续使用已缓存的译文。": "Supports plugins with verifiable sources in the official community directory. Cached translations remain available offline.",
  "重启后自动连接；离线时使用已缓存译文。断开连接会清除本机同步记录，之后需要重新连接并同步。": "Reconnects after restart and uses cached translations offline. Disconnecting clears local sync records; reconnect and synchronize to resume.",
  "断开此设备连接": "Disconnect this device",
  "已断开连接并清除本机同步记录；服务器上的短期凭据会自动过期。": "Disconnected and cleared local sync records. Short-lived server credentials expire automatically.",
  "上次操作 {time}：{message}": "Last action at {time}: {message}",
  "{language} · {connection}": "{language} · {connection}",
  "已连接": "Connected",
  "需要连接": "Connection required",
  "开启插件后自动获取译文。进度会随后台检查更新。": "Translations are fetched when you enable a plugin. Background checks update progress.",
  "本地化已暂停。请在设置中开启后继续。": "Localization is paused. Enable it in settings to resume.",
  "重新读取来源": "Recheck sources",
  "检查进度": "Check progress",
  "查看所选插件的最新处理进度和可用译文状态。": "Check the latest progress and translation availability for selected plugins.",
  "重新检查插件": "Recheck plugins",
  "检查已安装插件的变化并获取匹配译文；单个插件失败时使用其重试按钮。": "Check installed plugins for changes and fetch matching translations. Retry individual failed plugins using their retry buttons.",
  "译文可用 {ready} · 准备中 {processing} · 需处理 {attention}": "Available {ready} · Preparing {processing} · Needs attention {attention}",
  "清除搜索和筛选": "Clear search and filters",
  "进度与版本详情": "Progress and version details",
  "正在检查所选插件…": "Checking selected plugins…",
  "正在准备所选插件的译文…": "Preparing translations for selected plugins…",
  "译文可用": "Translations available",
  "部分译文可用": "Some translations available",
  "正在准备翻译": "Preparing translations",
  "需要处理": "Needs attention",
  "已关闭": "Off",
  "已暂停": "Paused",
  "暂无法确认来源": "Source temporarily unavailable",
  "处理补丁冲突": "Resolve patch conflict",

  "选择变化后会自动扫描并同步。": "Changes are scanned and synchronized automatically.",
  "连接语枢、选择目标语言和需要本地化的插件。": "Connect Trans-Hub, choose a target language, and select plugins to localize.",
  "自动识别插件已有语言，只补齐缺失界面，并随插件版本持续更新。": "Detect languages already provided by plugins, fill only missing UI, and stay current as plugins evolve.",
  "为官方社区插件补齐缺失界面译文；保留插件自带语言，并随精确版本安全更新。": "Fill missing UI translations for official community plugins, preserve their built-in language, and update safely with each exact version.",
  "插件自带译文优先": "Plugin translations first",
  "标明机器翻译与人工校对": "Machine and reviewed translations labeled",
  "不修改插件文件或笔记正文": "Plugin files and notes stay untouched",
  "仅支持官方社区插件": "Official community plugins only",
  "非社区插件缺少可验证的官方目录和版本来源。为避免对未知版本错误应用译文，语枢不会自动处理它们。": "Non-community plugins do not have a verifiable official catalog and version source. To avoid applying translations to an unknown version, Trans-Hub does not process them automatically.",
  "不会修改第三方插件文件或笔记正文。": "Third-party plugin files and note content are never modified.",
  "启用插件本地化": "Enable plugin localization",
  "自动翻译": "Automatic translation",
  "关闭后立即恢复被运行时替换的原文；重新开启后继续应用所选插件的已发布译文。": "Turn this off to restore runtime-replaced source text immediately. Turn it on again to apply published translations for selected plugins.",
  "翻译插件名称和说明": "Translate plugin names and descriptions",
  "高级兼容模式（会修改插件文件）": "Advanced compatibility (modifies plugin files)",
  "默认关闭。大多数界面文案可在运行时直接显示译文，不需要修改插件文件。少数插件把设置页单独渲染，运行时无法触及，才需要开启此模式。开启后，请在插件管理器中为符合条件的插件单独使用兼容补丁。系统只写入已发布、与当前版本完全匹配且位置可确认的静态文案，并先保存可恢复备份。动态文案、带变量的模板、未收录版本或无法确认写入位置的插件不会提供补丁，以免改坏插件。关闭后会恢复原文件；更改后请重启 Obsidian 或重新加载目标插件。": "Off by default. Most UI text is translated at runtime without modifying plugin files. A few plugins render settings pages separately, where runtime localization cannot reach, so this mode is needed only for them. After enabling it, use a compatibility patch for each eligible plugin in the plugin manager. The patch writes only published static text whose exact version and location are verified, after creating a recoverable backup. It is unavailable for dynamic text, templates with variables, unlisted versions, or locations that cannot be verified, so plugin code is not damaged. Turning it off restores the original file. Restart Obsidian or reload the target plugin after changes.",
  "已写入 {applied} 条静态界面译文；跳过 {skipped} 个插件，冲突 {conflicts} 个。重启或重新加载目标插件后生效。": "Wrote {applied} static UI translations; skipped {skipped} plugins and found {conflicts} conflicts. Restart or reload the target plugin to apply them.",
  "已恢复 {restored} 个插件文件；{conflicts} 个文件已被外部更新，未覆盖。": "Restored {restored} plugin files; {conflicts} externally changed files were left untouched.",
  "兼容补丁已允许。它只用于设置页等运行时无法覆盖的位置；请在插件管理器中为符合条件的插件单独使用。": "Compatibility patching is allowed. Use it only for settings pages and other places runtime localization cannot reach, and only for eligible plugins in the plugin manager.",
  "使用兼容补丁": "Use compatibility patch",
  "此插件的设置页无法由运行时本地化覆盖。仅写入已发布、与当前版本完全匹配且位置可确认的静态文案，并先保存备份；动态文案、带变量的模板和不匹配版本不会修改。": "This plugin's settings page cannot be covered by runtime localization. The patch writes only published static text whose exact version and location are verified, after saving a backup. It does not modify dynamic text, templates with variables, or mismatched versions.",
  "取消兼容补丁": "Remove compatibility patch",
  "恢复该插件文件的原始内容并删除补丁备份。重新加载目标插件后生效。": "Restore this plugin file's original content and remove the patch backup. Takes effect after reloading the target plugin.",
  "正在应用…": "Applying…",
  "正在取消…": "Removing…",
  "已取消兼容补丁：恢复 {restored} 个插件文件，冲突 {conflicts} 个。重新加载目标插件后生效。": "Removed the compatibility patch: restored {restored} plugin files with {conflicts} conflicts. Reload the target plugin to apply.",
  "该插件文件在补丁后被外部修改，无法安全恢复。是否强制用备份覆盖当前文件？": "This plugin file changed after patching and cannot be restored safely. Restore from the verified backup anyway?",
  "确认强制恢复": "Confirm forced restore",
  "此操作会覆盖该插件当前的 main.js；仅当备份摘要仍与原始文件一致时才会继续。": "This overwrites the plugin's current main.js. It continues only when the backup digest still matches the original file.",
  "保留当前文件": "Keep current file",
  "强制恢复": "Force restore",
  "已强制恢复 {restored} 个插件文件。重新加载目标插件后生效。": "Force-restored {restored} plugin files. Reload the target plugin to apply.",
  "已保留当前插件文件；可先重装该插件后再取消补丁。": "The current plugin file was kept. Reinstall the plugin before removing the patch if needed.",
  "兼容补丁写入冲突：插件文件与已发布制品不一致，已跳过。重新安装该插件后可重试。": "Compatibility patch conflict: the plugin file does not match the published artifact, so it was skipped. Reinstall the plugin to retry.",
  "暂无可写入的静态界面译文：本地目录与服务端权威目录尚未一致，或该插件暂无匹配的已发布静态译文。服务端目录更新后会自动可用。": "No static UI translations can be written yet: the local catalog and the server's authoritative catalog are not aligned, or the plugin has no matching published static translations. This becomes available automatically once the server catalog updates.",
  "该插件没有可写入的静态界面译文。": "This plugin has no static UI translations to write.",
  "默认开启。开启时显示译名和译文说明；关闭时显示官方名称和原始说明。尚无名称译文的插件会保留官方名称。": "On by default. Show translated names and descriptions when available; otherwise keep the official metadata.",
  "翻译为": "Translate to",
  "正在切换目标语言…": "Switching target language…",
  "正在验证公共目录条目…": "Verifying public directory entry…",
  "已提交公共目录发现，等待服务端处理": "Public directory discovery submitted; waiting for server processing.",
  "目录条目已被服务端阻断，当前不可由客户端重试。": "The server blocked this directory entry; the client cannot retry it.",
  "服务端已验证当前来源，正在建立本地化发布状态。": "The server verified the current source and is preparing localization publication.",
  "状态刷新失败；已保留上次结果，{failed} 个插件的状态可能已过期。": "Status refresh failed. The previous result was retained; {failed} plugin statuses may be stale.",
  "已刷新所选 {count} 个插件状态；{blocked} 个已被服务端阻断，当前不可由客户端重试。": "Refreshed {count} selected plugins; {blocked} were blocked by the server and cannot be retried by the client.",
  "{scope} {count} 个插件；{blocked} 个已被服务端阻断，当前不可由客户端重试。": "{scope} {count} plugins; {blocked} were blocked by the server and cannot be retried by the client.",
  "正在校验公共目录与当前权威版本": "Validating the public directory entry against the current authoritative version.",
  "当前权威版本正在解析并建立来源目录": "Parsing the current authoritative version and building its source catalog.",
  "当前权威版本正在翻译": "Translating the current authoritative version.",
  "译文正在生成可下载发布版本": "Preparing a downloadable published translation.",
  "译文已发布，等待客户端下载": "Translation published; waiting for the client to download it.",
  "当前权威版本暂无法公开发布": "The current authoritative version cannot be published publicly yet.",
  "目录条目暂无法处理。点击右侧“重试此插件”。": "This directory entry cannot be processed yet. Click \"Retry this plugin\" on the right.",
  "已切换目标语言；登录语枢后会继续同步。": "Target language switched. Synchronization continues after you connect Trans-Hub.",
  "插件自带的目标语言会优先保留，语枢只补齐仍显示原文的界面。插件自身界面也使用这里选择的语言。": "A plugin's own target-language text is preserved first, and Trans-Hub fills only UI that remains in the source language. This plugin also uses the language selected here.",
  "选择插件": "Choose plugins",
  "插件本地化": "Plugin localization",
  "插件管理": "Plugin manager",
  "管理已安装插件": "Manage installed plugins",
  "在可缩放的独立窗口中选择插件、查看来源与译文状态；状态刷新不会跳回列表顶部。": "Choose plugins and view their source and translation status in a resizable separate window; status updates keep your list position.",
  "打开插件管理器": "Open plugin manager",
  "打开插件本地化管理器": "Open plugin localization manager",
  "此设备无法打开独立窗口，已在工作区中打开插件管理器。": "This device cannot open a separate window, so the plugin manager opened in the workspace.",
  "本地化设置": "Localization settings",
  "显示当前已启用的第三方插件。只有能绑定到 Obsidian 官方目录可信 GitHub 来源的插件可以开启；其他插件仍会显示，并说明暂不可用的原因。": "Enabled third-party plugins are shown. Only plugins bound to a trusted GitHub source in the official Obsidian directory can be enabled; other plugins remain visible with an explanation.",
  "正在读取已启用插件…": "Reading enabled plugins…",
  "语枢已连接": "Trans-Hub connected",
  "连接语枢": "Connect Trans-Hub",
  "需要重新连接语枢": "Reconnect Trans-Hub",
  "此设备会在重启 Obsidian 后自动恢复连接；离线时继续使用已缓存的已发布译文。": "This device reconnects automatically after Obsidian restarts. Cached published translations remain available offline.",
  "此设备的授权已过期或被撤销。重新连接后会继续同步；已缓存译文仍可离线使用。": "This device authorization expired or was revoked. Reconnect to resume synchronization; cached translations remain available offline.",
  "将在系统默认浏览器中登录并授权此设备；Obsidian 内置浏览器无法完成回调。注册目前为邀请制，插件不会接触或保存账号密码。": "Sign in and authorize this device in your system browser. Obsidian's built-in browser cannot complete the callback. Registration is currently invite-only, and the plugin never handles or stores your password.",
  "一起完善插件本地化": "Help improve plugin localization",
  "当前多数语枢译文由机器翻译生成，并会明确标注未经人工校对。如果你熟悉某个插件或语言，欢迎参与翻译、校对和审查，让译文更准确，也能随插件版本持续维护。": "Most Trans-Hub translations are currently machine-generated and clearly labeled as not human reviewed. If you know a plugin or language well, join the translation, review, and proofreading effort to make localization more accurate and sustainable across plugin updates.",
  "查看进展并参与贡献": "View progress and contribute",
  "清除本机连接": "Clear device connection",
  "已清除本机连接信息；服务器上的短期凭据会自动过期。": "Device connection data cleared. Short-lived server credentials will expire automatically.",
  "在浏览器中连接": "Connect in browser",
  "重新连接": "Reconnect",
  "请在浏览器中完成登录和设备授权。": "Complete sign-in and device authorization in your browser.",
  "注册": "Register",
  "打开邀请制注册页面": "Open the invite-only registration page",
  "没有发现已启用的第三方插件。启用插件后重新打开此页面即可选择。": "No enabled third-party plugins were found. Enable a plugin and reopen this page to select it.",
  "读取插件失败：{message}": "Could not read plugins: {message}",
  "{count} 个已启用插件": "{count} enabled plugins",
  "搜索插件": "Search plugins",
  "搜索插件名称或 ID": "Search plugin name or ID",
  "全选": "Select all",
  "取消全选": "Deselect all",
  "刷新状态": "Refresh status",
  "读取所选插件的服务器收录、来源与译文状态（不重新扫描、不提交或重新验证本地文件）": "Read server cataloging, source, and translation status for selected plugins without rescanning, submitting, or revalidating local files.",
  "重新同步": "Resync",
  "重新扫描所选插件并只同步真实变化的译文提交；批量恢复请对单个插件使用“重试此插件”。": "Rescan selected plugins and synchronize only translations that actually changed; for bulk recovery, use “Retry this plugin” on individual plugins.",
  "按本地化状态筛选插件": "Filter plugins by localization status",
  "已选择 {selected}": "Selected {selected}",
  "已选择 {selected} / {total}": "Selected {selected} / {total}",
  "可本地化 {eligible} / 已启用 {total}": "{eligible} localizable / {total} enabled",
  "暂不支持": "Not supported yet",
  "来源待验证": "Source pending verification",
  "暂不支持：未找到可信 GitHub 来源": "Not supported yet: no trusted GitHub source was found",
  "来源待验证：暂时无法读取 Obsidian 官方目录": "Source pending verification: the official Obsidian directory is temporarily unavailable",
  "切换 {pluginName} 本地化": "Toggle localization for {pluginName}",
  "{pluginName} 不可开启：{reason}": "{pluginName} cannot be enabled: {reason}",
  "没有匹配的插件。": "No matching plugins.",
  "重试此插件": "Retry this plugin",
  "重新检查并重试 {pluginName}，无需关闭本地化开关": "Check and retry {pluginName}; you do not need to turn localization off.",
  "重试 {pluginName} 本地化": "Retry localization for {pluginName}",
  "正在重试…": "Retrying…",
  "正在重试 {pluginName}…": "Retrying {pluginName}…",
  "处理失败：{message}": "Processing failed: {message}",
  "正在扫描所选插件…": "Scanning selected plugins…",
  "正在刷新所选插件状态…": "Refreshing selected plugin status…",
  "正在重新同步所选插件…": "Resyncing selected plugins…",
  "已刷新所选 {count} 个插件状态；{failed} 个需要重试，请点击对应插件的“重试此插件”。": "Refreshed status for {count} selected plugins; {failed} need retry. Click “Retry this plugin” for those.",
  "已刷新所选 {count} 个插件状态；{waiting} 个仍在处理中。": "Refreshed status for {count} selected plugins; {waiting} are still being processed.",
  "已刷新所选 {count} 个插件状态；{waiting} 个正在处理，其中 {export} 个正在自动发布。": "Refreshed status for {count} selected plugins; {waiting} are being processed, including {export} being published automatically.",
  "已刷新所选 {count} 个插件状态；{waiting} 个仍在处理，另有 {export} 个正在自动发布。": "Refreshed status for {count} selected plugins; {waiting} are still being processed, with {export} others being published automatically.",
  "已刷新所选 {count} 个插件状态；{export} 个译文已生成，服务器正在自动发布。": "Refreshed status for {count} selected plugins; {export} translations are generated and the server is publishing them automatically.",
  "已刷新所选 {count} 个插件状态，安全应用 {translations} 条译文。": "Refreshed status for {count} selected plugins and safely applied {translations} translations.",
  "已刷新所选 {count} 个插件状态，目前没有新译文。": "Refreshed status for {count} selected plugins. No new translations.",
  "语枢已连接，此设备以后会自动恢复连接。": "Trans-Hub connected. This device will reconnect automatically.",
  "连接成功，正在同步所选插件…": "Connected. Synchronizing selected plugins…",
  "语枢连接失败。": "Could not connect to Trans-Hub.",
  "插件目录已变化，请先在插件管理器中重新同步该插件。": "The plugin catalog changed. Resync this plugin in the plugin manager first.",
  "已停止所有插件翻译。": "Translation is disabled for all plugins.",
  "所选插件当前没有可处理的本地化内容。": "The selected plugins have no localizable content to process.",
  "已扫描 {count} 个插件；登录语枢后会继续同步。": "Scanned {count} plugins. Synchronization continues after you connect Trans-Hub.",
  "{scope} {count} 个插件；登录语枢后会继续同步。": "{scope} {count} plugins. Synchronization continues after you connect Trans-Hub.",
  "已检查 {count} 个插件；新增 {requested} 个本地化需求，{waiting} 个正在由服务器处理或等待审查。": "Checked {count} plugins; added {requested} localization requests, with {waiting} being processed or awaiting review.",
  "{scope} {count} 个插件；新增 {requested} 个本地化需求，{waiting} 个正在处理，其中 {export} 个正在自动发布": "{scope} {count} plugins; created {requested} localization requests, with {waiting} being processed, including {export} being published automatically",
  "{scope} {count} 个插件；新增 {requested} 个本地化需求，{waiting} 个正在处理": "{scope} {count} plugins; created {requested} localization requests, with {waiting} still being processed",
  "{scope} {count} 个插件；{export} 个译文已生成，服务器正在自动发布。": "{scope} {count} plugins; {export} translations are generated and the server is publishing them automatically.",
  "已更新 {count} 个插件，本机安全应用 {translations} 条译文。": "Updated {count} plugins and safely applied {translations} translations on this device.",
  "{scope}更新 {count} 个插件，本机安全应用 {translations} 条译文。": "{scope} {count} plugins and safely applied {translations} translations on this device.",
  "已检查 {count} 个插件，目前没有新译文。": "Checked {count} plugins. No new translations are available.",
  "{scope} {count} 个插件，目前没有新译文。": "{scope} {count} plugins. No new translations are available.",
  "全部状态": "All statuses",
  "已本地化": "Localized",
  "目录待同步": "Catalog updating",
  "等待发布": "Awaiting publication",
  "自动发布中": "Publishing automatically",
  "权威校验": "Authority verification",
  "需要登录": "Connection required",
  "未收录": "Not cataloged",
  "尚未提交本地化需求": "No localization request has been submitted yet",
  "正在准备首次本地化…": "Preparing initial localization…",
  "未启用本地化": "Localization is not enabled",
  "等待首次自动收录": "Awaiting initial automatic cataloging",
  "正在首次自动收录…": "Cataloging automatically for the first time…",
  "本地安装与权威目录的精确制品不一致，已暂停同步": "The local installation differs from the authoritative exact artifact; synchronization is paused",
  "分发受限": "Distribution restricted",
  "需要重试": "Retry needed",
  "处理失败": "Processing failed",
  "保留原文": "Original preserved",
  "已准备 {translated}/{total} 条匹配译文（{percent}%），{missing} 条等待发布": "Prepared {translated}/{total} matching translations ({percent}%); {missing} awaiting publication",
  "已获取 {translated}/{total} 条匹配译文（{percent}%），{missing} 条尚未发布": "Fetched {translated}/{total} matching translations ({percent}%); {missing} not yet published",
  "已获取 {translated}/{total} 条匹配译文（{percent}%）": "Fetched {translated}/{total} matching translations ({percent}%)",
  "覆盖范围": "Coverage",
  "{scope} {translated}/{total}": "{scope} {translated}/{total}",
  "插件自带覆盖范围明细待服务端提供": "Scope details for plugin-native coverage are not yet available from the server",
  "可安全应用 {translated}/{total} 条匹配译文": "Safe to apply: {translated}/{total} matching translations",
  "可安全应用 {translated}/{total} 条匹配译文，{missing} 条暂无权威译文": "Safe to apply: {translated}/{total} matching translations; {missing} have no authoritative translation",
  "可安全应用 {translated}/{total} 条匹配译文，{missing} 条暂不可安全应用": "Safe to apply: {translated}/{total} matching translations; {missing} cannot be safely applied yet",
  "可安全应用 {translated}/{total} 条匹配译文，{missing} 条因公开分发策略不可用暂无译文": "Safe to apply: {translated}/{total} matching translations; {missing} are unavailable because public distribution policy is unavailable",
  "本地目录与服务器权威目录待同步": "The local catalog and authoritative server catalog need synchronization",
  "暂无法公开发布：许可证证据已确认，服务端正在生成公开分发策略": "Cannot publish yet: license evidence is verified and the server is generating the public distribution policy",
  "无法公开发布：上游许可证不在当前安全分发范围": "Cannot publish: the upstream license is outside the current safe distribution scope",
  "无法公开发布：当前来源的许可证明确禁止公开分发": "Cannot publish: the current source license explicitly prohibits public distribution",
  "暂无法公开发布：当前来源的许可证需要人工确认": "Cannot publish yet: the current source license requires manual review",
  "无法公开发布：缺少当前精确版本的许可证证据": "Cannot publish: license evidence is missing for this exact version",
  "无法公开发布：当前来源的许可证证据存在冲突，服务器无法唯一确认许可证": "Cannot publish: the current source has conflicting license evidence, so the server cannot uniquely verify its license",
  "无法公开发布：当前精确版本存在冲突的公开分发策略": "Cannot publish: this exact version has conflicting public distribution policies",
  "无法公开发布：当前来源版本已下架": "Cannot publish: the current source version has been withdrawn",
  "暂无法公开发布：当前来源与权威来源不一致，需重新收录精确来源版本": "Cannot publish yet: the current source differs from the authoritative source and the exact source version must be ingested again",
  "无法公开发布：当前来源未通过权威来源校验": "Cannot publish: the current source did not pass authoritative source verification",
  "无法公开发布：管理员已关闭当前精确版本的公开分发": "Cannot publish: an administrator disabled public distribution for this exact version",
  "无法公开发布：服务器无权为当前来源建立公开分发策略": "Cannot publish: the server is not authorized to create a public distribution policy for this source",
  "无法公开发布：当前来源的权威证据无效": "Cannot publish: the authority evidence for the current source is invalid",
  "无法公开发布：权威来源校验多次失败，服务器已停止自动重试": "Cannot publish: authoritative source verification failed repeatedly and the server stopped retrying",
  "服务器正在校验当前精确版本的权威来源与许可证": "The server is verifying the authoritative source and license for this exact version",
  "无法公开发布：当前精确版本的公开分发策略不可用": "Cannot publish: no public distribution policy is available for this exact version",
  "服务器正在更新目录身份": "The server is updating catalog identity",
  "服务器目录正在更新：{scopes}": "The server catalog is updating: {scopes}",
  "可安全应用 {count} 条精确命中译文": "Safe to apply: {count} exact-match translations",
  "目录范围": "catalog scopes",
  "插件界面": "plugin UI",
  "名称与说明": "names and descriptions",
  "已沿用 {translated}/{total} 条安全译文": "Reused {translated}/{total} safe translations",
  "已本地化 {count} 条": "Localized {count} strings",
  "已获取 {count} 条缓存译文，等待当前目录匹配": "Fetched {count} cached translations; awaiting a match with the current catalog",
  "当前使用 {version} 的本地化译文；插件可继续使用，建议升级至 {version} 以获得最佳匹配": "Using localization for {version}; this plugin can continue to work, but updating to {version} provides the best match",
  "登录后同步": "Connect to synchronize",
  "重新连接后继续同步": "Reconnect to continue synchronization",
  "本地化需求未被接受。点击右侧“重试此插件”。": "The localization request was not accepted. Select “Retry this plugin” on the right.",
  "需求未被接受。点击右侧“重试此插件”。": "The request was not accepted. Select “Retry this plugin” on the right.",
  "同步失败：{message}。点击右侧“重试此插件”，无需关闭开关。": "Synchronization failed: {message}. Select “Retry this plugin” on the right; you do not need to turn localization off.",
  "机器翻译无法安全处理当前来源中的复杂占位符；该条将保留原文。": "Machine translation cannot safely process a complex placeholder in this source, so the original text will be preserved.",
  "机器翻译失败，服务器已停止自动重试。点击右侧“重试此插件”。": "Machine translation failed and automatic server retries have stopped. Select “Retry this plugin” on the right.",
  "等待目标语言译文发布": "Awaiting target-language publication",
  "等待本地化需求处理": "Localization request is being processed",
  "等待来源收录": "Awaiting source cataloging",
  "等待可信来源收录": "Awaiting trusted source cataloging",
  "已建立 {count} 条缺失本地化需求，等待机器翻译": "Created {count} missing localization requests; awaiting machine translation",
  "机器翻译排队中：{queued}/{total} 条": "Machine translation queued: {queued}/{total}",
  "机器翻译中：已完成 {succeeded}/{total} 条，正在处理 {running} 条": "Machine translation running: {succeeded}/{total} complete, {running} in progress",
  "机器翻译暂时失败，服务器将自动重试（第 {attempt}/5 次）": "Machine translation failed temporarily. The server will retry automatically (attempt {attempt}/5)",
  "翻译已完成 {succeeded}/{total} 条，等待译文制品发布": "Translation complete: {succeeded}/{total}. Awaiting translation package publication",
  "译文已发布，等待客户端回拉": "Translations published. Awaiting client download",
  "译文制品已生成，等待服务端公共目录更新": "Translation package created. Awaiting public directory update",
  "插件自带目标语言，已覆盖 {count} 条": "Plugin provides the target language for {count} strings",
  "插件自带 {count}": "Plugin native {count}",
  "语枢已校对 {count}": "Trans-Hub reviewed {count}",
  "语枢校对修正 {count}": "Trans-Hub reviewed correction {count}",
  "语枢机翻 {count}（未经人工校对）": "Trans-Hub machine translated {count} (not human reviewed)",
  "语枢已发布（未分类）{count}": "Trans-Hub published, unclassified {count}",
  "权威目录 {count} 条": "Authoritative catalog: {count} entries",
  "当前目录 {count} 条": "Current catalog: {count} entries",
  "语枢已发布 {count}": "Trans-Hub published {count}",
  "待补 {count}": "Missing {count}",
  "插件自带 {count} 条（范围明细待同步）": "Plugin native {count} strings (scope details pending synchronization)",
  "源语言，无需翻译": "Source language · no translation needed",
  "服务器暂时无法查询插件处理状态，请稍后重试。": "The server cannot check plugin processing status right now. Try again later.",
  "服务器暂时无法完成请求，请稍后重试。": "The server cannot complete this request right now. Try again later.",
  "{summary}；{failed} 个需要重试，请点击对应插件的“重试此插件”。": "{summary}; {failed} need a retry. Select “Retry this plugin” for each affected plugin.",
  "已检查 {count} 个插件；{failed} 个需要重试，请点击对应插件的“重试此插件”。": "Checked {count} plugins; {failed} need a retry. Select “Retry this plugin” for each affected plugin.",
  "{scope} {count} 个插件；{failed} 个需要重试，请点击对应插件的“重试此插件”。": "{scope} {count} plugins; {failed} need a retry. Select “Retry this plugin” for each affected plugin.",
  "已检查 {count} 个插件；新增 {requested} 个本地化需求，{waiting} 个仍在处理中": "Checked {count} plugins; created {requested} localization requests, with {waiting} still processing",
  "{scope} {count} 个插件；新增 {requested} 个本地化需求，{waiting} 个仍在处理中": "{scope} {count} plugins; created {requested} localization requests, with {waiting} still processing",
  "翻译已完成 {succeeded}/{total} 条，正在生成可下载包": "Translation completed for {succeeded}/{total} items; generating a downloadable package",
  "已": "Updated",
  "已检查": "Checked",
  "已检查所选": "Checked selected",
  "已更新所选": "Updated selected",
  "已重试": "Retried",
  "已重试并更新": "Retried and updated",
  "此设备的语枢授权已失效，请重新连接。已缓存译文仍可继续使用。": "This device's Trans-Hub authorization has expired. Reconnect to continue; cached translations remain available.",
  "操作：{operation}": "Operation: {operation}",
  "操作：{operation}，HTTP {status}": "Operation: {operation}, HTTP {status}",
  "{message}（{suffix}）": "{message} ({suffix})",
  "扫描已安装插件的界面文案": "Scan installed plugin UI strings",
  "扫描插件文案": "Scan plugin strings",
  "扫描完成：{plugins} 个插件，{strings} 条文案，{changed} 个目录有变化。": "Scan complete: {plugins} plugins, {strings} strings, {changed} changed catalogs.",
  "同步已安装插件的翻译": "Synchronize installed plugin translations",
  "同步插件翻译": "Synchronize plugin translations",
  "同步完成：新增需求 {requested}，拉取 {pulled}，处理中或待审查 {waiting}。": "Synchronization complete: {requested} new requests, {pulled} pulled, {waiting} processing or awaiting review.",
  "应用已缓存的插件译文": "Apply cached plugin translations",
  "{label}失败：{message}": "{label} failed: {message}",
  "万语汇于一枢，创想行于无碍": "Languages converge. Ideas move freely.",
  "关于语枢": "About Trans-Hub",
  "连接全球生态，沉淀语言资产": "Connect global ecosystems. Build lasting language assets.",
  "Trans-Hub —— AI 时代的全球本地化基础设施": "Trans-Hub — localization infrastructure for the AI era",
  "品牌定位": "Brand positioning",
  "语枢（Trans-Hub）不是普通翻译工具，而是连接数字生态与全球语言的本地化基础设施。": "Trans-Hub is not an ordinary translation tool. It is localization infrastructure connecting digital ecosystems with languages worldwide.",
  "AI 正在让语言转换变得越来越容易，但真正困难的是，让不断增长的多语言内容保持一致、可维护，并持续演进。": "AI is making language conversion easier, but the real challenge is keeping growing multilingual content consistent, maintainable, and continuously evolving.",
  "语枢将本地化从一次性的翻译流程，升级为可持续发展的语言资产体系。": "Trans-Hub turns localization from a one-off translation process into a sustainable language asset system.",
  "通过内容身份管理、智能翻译、协作审核、版本追踪和生态连接，让软件、游戏、社区项目与数字生态能够持续走向全球。": "Through content identity, intelligent translation, collaborative review, version tracking, and ecosystem connectivity, software, games, community projects, and digital ecosystems can keep reaching global audiences.",
  "了解语枢": "Learn about Trans-Hub",
};

let activeLocale: TargetLocale = "zh-CN";

const CLIENT_DISPLAY_NAMES = new Set([
  "语枢 · 插件本地化",
  "Trans-Hub Localizer",
]);

export function setClientLocale(locale: TargetLocale): void {
  activeLocale = locale;
}

export function clientLocale(): TargetLocale {
  return activeLocale;
}

export function localizedClientName(): string {
  return activeLocale === "zh-CN" ? "语枢 · 插件本地化" : "Trans-Hub Localizer";
}

export function isClientDisplayName(value: string): boolean {
  return CLIENT_DISPLAY_NAMES.has(value);
}

export function translate(source: string, parameters: MessageParameters = {}): string {
  const template = activeLocale === "zh-CN" ? source : ENGLISH_MESSAGES[source] ?? source;
  return Object.entries(parameters).reduce(
    (message, [key, value]) => message.replaceAll(`{${key}}`, String(value)),
    template,
  );
}
